#!/bin/bash

# compila archivo latex con bibliografia .bib
# escibir nombre de archivo sin extension

FILE=tesis

pdflatex  -shell-escape $FILE
bibtex $FILE
pdflatex  -shell-escape $FILE
pdflatex  -shell-escape $FILE
